[Interface]
PrivateKey = yAEWI0HIphcem5nNRFRbL0dVL8MwcXdAoDN4TF2461M=
Address = 10.0.39.203/24
DNS = 10.0.39.1

[Peer]
# Helsinki Hub Public Key (Verified Shard)
PublicKey = 6rG+T****************************************
Endpoint = 204.168.138.60:51820
AllowedIPs = 10.0.39.0/24
PersistentKeepalive = 25
