# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mesh_proto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mesh_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10mesh_proto.proto\x12\x05proto\"_\n\x0e\x41gentHeartbeat\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\x12\x1a\n\x12intelligence_level\x18\x04 \x01(\x05\"A\n\x0bStateUpdate\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x01\x12\x0e\n\x06\x61\x63tive\x18\x03 \x01(\x08\"\x1d\n\tTaskLease\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"6\n\x0eTaskAssignment\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\rWalletRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"1\n\x0eWalletResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x01\x12\x0e\n\x06staked\x18\x02 \x01(\x01\"0\n\x0cStakeRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x32\x9c\x02\n\rSovereignMesh\x12\x33\n\tHeartbeat\x12\x15.proto.AgentHeartbeat\x1a\x0f.proto.Response\x12\x30\n\tSyncState\x12\x12.proto.StateUpdate\x1a\x0f.proto.Response\x12\x36\n\x0bRequestTask\x12\x10.proto.TaskLease\x1a\x15.proto.TaskAssignment\x12\x39\n\nGetBalance\x12\x14.proto.WalletRequest\x1a\x15.proto.WalletResponse\x12\x31\n\tStakeCoin\x12\x13.proto.StakeRequest\x1a\x0f.proto.ResponseB*Z(github.com/pqr-info/sovereign-mesh/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mesh_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/pqr-info/sovereign-mesh/proto'
  _globals['_AGENTHEARTBEAT']._serialized_start=27
  _globals['_AGENTHEARTBEAT']._serialized_end=122
  _globals['_STATEUPDATE']._serialized_start=124
  _globals['_STATEUPDATE']._serialized_end=189
  _globals['_TASKLEASE']._serialized_start=191
  _globals['_TASKLEASE']._serialized_end=220
  _globals['_TASKASSIGNMENT']._serialized_start=222
  _globals['_TASKASSIGNMENT']._serialized_end=276
  _globals['_RESPONSE']._serialized_start=278
  _globals['_RESPONSE']._serialized_end=322
  _globals['_WALLETREQUEST']._serialized_start=324
  _globals['_WALLETREQUEST']._serialized_end=357
  _globals['_WALLETRESPONSE']._serialized_start=359
  _globals['_WALLETRESPONSE']._serialized_end=408
  _globals['_STAKEREQUEST']._serialized_start=410
  _globals['_STAKEREQUEST']._serialized_end=458
  _globals['_SOVEREIGNMESH']._serialized_start=461
  _globals['_SOVEREIGNMESH']._serialized_end=745
# @@protoc_insertion_point(module_scope)
