package governance

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"math"
	"math/big"
)

// AgentOutput represents the structure generated by each individual agent during a proposal cycle.
type AgentOutput struct {
	AgentID    string      `json:"agent_id"`
	RoleID     string      `json:"role_id"`     // e.g., "game-theory", "human-design", "general"
	LocaleID   string      `json:"locale_id"`   // geographical/mesh location reference
	Ck         []float64   `json:"ck"`          // cognitive vector slice
	Alpha      float64     `json:"alpha"`       // agentic weight
	Proposal   interface{} `json:"proposal"`    // the actual suggested action/flow value
	Confidence float64     `json:"confidence"`  // confidence score [0, 1]
}

// Agent defines the interface for all diverse agents in the AMLN network.
type Agent interface {
	AgentID() string
	RoleID() string
	GenerateProposal() AgentOutput
	ReceiveVerdict(verdict FinalVerdict, decision CouncilDecision)
	Freeze()
	Resume()
	Snapshot() AgentStateSnapshot
	Entropy() float64
	LineageDrift() float64
	StrategyVariance() float64
}

// BaseAgent contains properties common to all agents.
type BaseAgent struct {
	ID        string
	Role      string
	Locale    string
	Strategy  []float64
	Alpha     float64
	Precision float64
	IsFrozen  bool
}

func (a *BaseAgent) Freeze() {
	a.IsFrozen = true
}

func (a *BaseAgent) Resume() {
	a.IsFrozen = false
}

func (a *BaseAgent) Snapshot() AgentStateSnapshot {
	return AgentStateSnapshot{
		Lineage:     []float64{0.1, 0.2},
		Entropy:     0.5,
		SELStrategy: a.Strategy,
		RoleVector:  []float64{0.5, 0.6},
		LocaleID:    a.Locale,
		CognitiveK:  a.Strategy,
		Alpha:       a.Alpha,
		RoleID:      a.Role,
	}
}

func (a *BaseAgent) Entropy() float64 {
	// Simple non-anthropomorphic heuristic: base it on strategy variance or alpha
	var sum float64
	for _, v := range a.Strategy {
		sum += v * v
	}
	if len(a.Strategy) == 0 {
		return 0.5
	}
	return math.Min(1.0, math.Max(0.0, sum/float64(len(a.Strategy))))
}

func (a *BaseAgent) LineageDrift() float64 {
	// Simple representation of drift from an initial state
	return math.Abs(a.Alpha - 0.5)
}

func (a *BaseAgent) StrategyVariance() float64 {
	var sum, sumSq float64
	n := float64(len(a.Strategy))
	if n == 0 {
		return 0.0
	}
	for _, v := range a.Strategy {
		sum += v
		sumSq += v * v
	}
	mean := sum / n
	return (sumSq / n) - (mean * mean)
}

// ------------------------------------------------------------
// Game Theory Agent
// ------------------------------------------------------------

type GameTheoryAgent struct {
	BaseAgent
}

func NewGameTheoryAgent(id string, size int, locale string) *GameTheoryAgent {
	strategy := make([]float64, size)
	for i := range strategy {
		strategy[i] = getRandomFloatValue()
	}
	return &GameTheoryAgent{
		BaseAgent: BaseAgent{
			ID:        id,
			Role:      "game-theory",
			Locale:    locale,
			Strategy:  strategy,
			Alpha:     0.7,
			Precision: 0.8,
		},
	}
}

func (a *GameTheoryAgent) AgentID() string { return a.ID }
func (a *GameTheoryAgent) RoleID() string  { return a.Role }

func (a *GameTheoryAgent) GenerateProposal() AgentOutput {
	// Mutate strategy slightly
	for i := range a.Strategy {
		a.Strategy[i] += getRandomFloatValue() * 0.02
	}
	return AgentOutput{
		AgentID:    a.ID,
		RoleID:     a.Role,
		LocaleID:   a.Locale,
		Ck:         a.Strategy,
		Alpha:      a.Alpha,
		Proposal:   "optimize-payoff-matrix",
		Confidence: a.Precision,
	}
}

func (a *GameTheoryAgent) ReceiveVerdict(verdict FinalVerdict, decision CouncilDecision) {
	// Reinforcement learn: improve confidence on success, decay/adapt on veto
	if verdict.Approved {
		a.Precision = 0.9*a.Precision + 0.1
	} else {
		a.Precision = 0.95 * a.Precision
	}
}

// ------------------------------------------------------------
// Human Design Agent
// ------------------------------------------------------------

type HumanDesignAgent struct {
	BaseAgent
}

func NewHumanDesignAgent(id string, size int, locale string) *HumanDesignAgent {
	strategy := make([]float64, size)
	for i := range strategy {
		strategy[i] = getRandomFloatValue()
	}
	return &HumanDesignAgent{
		BaseAgent: BaseAgent{
			ID:        id,
			Role:      "human-design",
			Locale:    locale,
			Strategy:  strategy,
			Alpha:     0.6,
			Precision: 0.75,
		},
	}
}

func (a *HumanDesignAgent) AgentID() string { return a.ID }
func (a *HumanDesignAgent) RoleID() string  { return a.Role }

func (a *HumanDesignAgent) GenerateProposal() AgentOutput {
	for i := range a.Strategy {
		a.Strategy[i] += getRandomFloatValue() * 0.015
	}
	return AgentOutput{
		AgentID:    a.ID,
		RoleID:     a.Role,
		LocaleID:   a.Locale,
		Ck:         a.Strategy,
		Alpha:      a.Alpha,
		Proposal:   "align-user-experience",
		Confidence: a.Precision,
	}
}

func (a *HumanDesignAgent) ReceiveVerdict(verdict FinalVerdict, decision CouncilDecision) {
	if verdict.Approved {
		a.Precision = 0.92*a.Precision + 0.08
	} else {
		a.Precision = 0.9 * a.Precision
	}
}

// ------------------------------------------------------------
// General SEN Agent
// ------------------------------------------------------------

type GeneralSENAgent struct {
	BaseAgent
}

func NewGeneralSENAgent(id string, size int, locale string) *GeneralSENAgent {
	strategy := make([]float64, size)
	for i := range strategy {
		strategy[i] = getRandomFloatValue()
	}
	return &GeneralSENAgent{
		BaseAgent: BaseAgent{
			ID:        id,
			Role:      "general",
			Locale:    locale,
			Strategy:  strategy,
			Alpha:     0.8,
			Precision: 0.85,
		},
	}
}

func (a *GeneralSENAgent) AgentID() string { return a.ID }
func (a *GeneralSENAgent) RoleID() string  { return a.Role }

func (a *GeneralSENAgent) GenerateProposal() AgentOutput {
	for i := range a.Strategy {
		a.Strategy[i] += getRandomFloatValue() * 0.025
	}
	return AgentOutput{
		AgentID:    a.ID,
		RoleID:     a.Role,
		LocaleID:   a.Locale,
		Ck:         a.Strategy,
		Alpha:      a.Alpha,
		Proposal:   "process-cognition-cycle",
		Confidence: a.Precision,
	}
}

func (a *GeneralSENAgent) ReceiveVerdict(verdict FinalVerdict, decision CouncilDecision) {
	if verdict.Approved {
		a.Precision = 0.88*a.Precision + 0.12
	} else {
		a.Precision = 0.92 * a.Precision
	}
}

// Initialize195Agents constructs the full three-tier agent cohort.
func Initialize195Agents(vectorSize int) []Agent {
	agents := make([]Agent, 195)
	locales := []string{"US-EAST", "EU-CENTRAL", "AP-NORTHEAST", "SA-EAST"}

	// 64 Game Theory
	for i := 0; i < 64; i++ {
		locale := locales[i%len(locales)]
		agents[i] = NewGameTheoryAgent(fmt.Sprintf("game-theory-agent-%d", i), vectorSize, locale)
	}
	// 64 Human Design
	for i := 0; i < 64; i++ {
		locale := locales[i%len(locales)]
		agents[64+i] = NewHumanDesignAgent(fmt.Sprintf("human-design-agent-%d", i), vectorSize, locale)
	}
	// 67 General SEN
	for i := 0; i < 67; i++ {
		locale := locales[i%len(locales)]
		agents[128+i] = NewGeneralSENAgent(fmt.Sprintf("general-sen-agent-%d", i), vectorSize, locale)
	}

	return agents
}

// Helpers
func getRandomFloatValue() float64 {
	nBig, err := rand.Int(rand.Reader, big.NewInt(1000))
	if err != nil {
		return 0.0
	}
	return (float64(nBig.Int64()) / 1000.0) - 0.5
}

func getRandomIntValue() int64 {
	var b [8]byte
	_, _ = rand.Read(b[:])
	return int64(binary.BigEndian.Uint64(b[:]))
}
