# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mesh_proto_pb2 as mesh__proto__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_proto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SovereignMeshStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/proto.SovereignMesh/Heartbeat',
                request_serializer=mesh__proto__pb2.AgentHeartbeat.SerializeToString,
                response_deserializer=mesh__proto__pb2.Response.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/proto.SovereignMesh/SyncState',
                request_serializer=mesh__proto__pb2.StateUpdate.SerializeToString,
                response_deserializer=mesh__proto__pb2.Response.FromString,
                _registered_method=True)
        self.RequestTask = channel.unary_unary(
                '/proto.SovereignMesh/RequestTask',
                request_serializer=mesh__proto__pb2.TaskLease.SerializeToString,
                response_deserializer=mesh__proto__pb2.TaskAssignment.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/proto.SovereignMesh/GetBalance',
                request_serializer=mesh__proto__pb2.WalletRequest.SerializeToString,
                response_deserializer=mesh__proto__pb2.WalletResponse.FromString,
                _registered_method=True)
        self.StakeCoin = channel.unary_unary(
                '/proto.SovereignMesh/StakeCoin',
                request_serializer=mesh__proto__pb2.StakeRequest.SerializeToString,
                response_deserializer=mesh__proto__pb2.Response.FromString,
                _registered_method=True)


class SovereignMeshServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Agents register their presence and status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Remote state synchronization (Proxy for memory bus)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTask(self, request, context):
        """Orchestration: Agents pull tasks from the controller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Cobalt Chrome Wallet API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StakeCoin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SovereignMeshServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=mesh__proto__pb2.AgentHeartbeat.FromString,
                    response_serializer=mesh__proto__pb2.Response.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=mesh__proto__pb2.StateUpdate.FromString,
                    response_serializer=mesh__proto__pb2.Response.SerializeToString,
            ),
            'RequestTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTask,
                    request_deserializer=mesh__proto__pb2.TaskLease.FromString,
                    response_serializer=mesh__proto__pb2.TaskAssignment.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=mesh__proto__pb2.WalletRequest.FromString,
                    response_serializer=mesh__proto__pb2.WalletResponse.SerializeToString,
            ),
            'StakeCoin': grpc.unary_unary_rpc_method_handler(
                    servicer.StakeCoin,
                    request_deserializer=mesh__proto__pb2.StakeRequest.FromString,
                    response_serializer=mesh__proto__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SovereignMesh', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SovereignMesh', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SovereignMesh(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SovereignMesh/Heartbeat',
            mesh__proto__pb2.AgentHeartbeat.SerializeToString,
            mesh__proto__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SovereignMesh/SyncState',
            mesh__proto__pb2.StateUpdate.SerializeToString,
            mesh__proto__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SovereignMesh/RequestTask',
            mesh__proto__pb2.TaskLease.SerializeToString,
            mesh__proto__pb2.TaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SovereignMesh/GetBalance',
            mesh__proto__pb2.WalletRequest.SerializeToString,
            mesh__proto__pb2.WalletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StakeCoin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SovereignMesh/StakeCoin',
            mesh__proto__pb2.StakeRequest.SerializeToString,
            mesh__proto__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
