.TH GMAN 1 "2026-04-01" "v1.0" "Sovereign Mesh Manual"
.SH NAME
gman \- Sovereign Mesh Manual pager
.SH SYNOPSIS
.B gman
[COMMAND]
.SH DESCRIPTION
Standardized manual system for GSH-MESH. All functional commands are lowercase. 
STAGED functionality is ALL CAPS.
.SH SEE ALSO
mesh-logs(1), mesh-colors(1)
