// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/swarm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SwarmCommunication_SendPacket_FullMethodName          = "/swarm.SwarmCommunication/SendPacket"
	SwarmCommunication_StreamDeliberation_FullMethodName  = "/swarm.SwarmCommunication/StreamDeliberation"
	SwarmCommunication_ProvisionShortcode_FullMethodName  = "/swarm.SwarmCommunication/ProvisionShortcode"
	SwarmCommunication_GetActiveShortcodes_FullMethodName = "/swarm.SwarmCommunication/GetActiveShortcodes"
	SwarmCommunication_ExecuteStrike_FullMethodName       = "/swarm.SwarmCommunication/ExecuteStrike"
	SwarmCommunication_SyncBlackhole_FullMethodName       = "/swarm.SwarmCommunication/SyncBlackhole"
	SwarmCommunication_OpenExecutionStream_FullMethodName = "/swarm.SwarmCommunication/OpenExecutionStream"
)

// SwarmCommunicationClient is the client API for SwarmCommunication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwarmCommunicationClient interface {
	// Port 1111: Logged Consensus
	SendPacket(ctx context.Context, in *SwarmPacket, opts ...grpc.CallOption) (*SwarmPacket, error)
	StreamDeliberation(ctx context.Context, opts ...grpc.CallOption) (SwarmCommunication_StreamDeliberationClient, error)
	ProvisionShortcode(ctx context.Context, in *ShortcodeRequest, opts ...grpc.CallOption) (*ShortcodeResponse, error)
	GetActiveShortcodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShortcodeList, error)
	// Legacy AELLOK Compatibility
	ExecuteStrike(ctx context.Context, in *StrikeRequest, opts ...grpc.CallOption) (*StrikeResponse, error)
	SyncBlackhole(ctx context.Context, opts ...grpc.CallOption) (SwarmCommunication_SyncBlackholeClient, error)
	// SWEN Execution Stream
	OpenExecutionStream(ctx context.Context, opts ...grpc.CallOption) (SwarmCommunication_OpenExecutionStreamClient, error)
}

type swarmCommunicationClient struct {
	cc grpc.ClientConnInterface
}

func NewSwarmCommunicationClient(cc grpc.ClientConnInterface) SwarmCommunicationClient {
	return &swarmCommunicationClient{cc}
}

func (c *swarmCommunicationClient) SendPacket(ctx context.Context, in *SwarmPacket, opts ...grpc.CallOption) (*SwarmPacket, error) {
	out := new(SwarmPacket)
	err := c.cc.Invoke(ctx, SwarmCommunication_SendPacket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmCommunicationClient) StreamDeliberation(ctx context.Context, opts ...grpc.CallOption) (SwarmCommunication_StreamDeliberationClient, error) {
	stream, err := c.cc.NewStream(ctx, &SwarmCommunication_ServiceDesc.Streams[0], SwarmCommunication_StreamDeliberation_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &swarmCommunicationStreamDeliberationClient{stream}
	return x, nil
}

type SwarmCommunication_StreamDeliberationClient interface {
	Send(*SwarmPacket) error
	Recv() (*SwarmPacket, error)
	grpc.ClientStream
}

type swarmCommunicationStreamDeliberationClient struct {
	grpc.ClientStream
}

func (x *swarmCommunicationStreamDeliberationClient) Send(m *SwarmPacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *swarmCommunicationStreamDeliberationClient) Recv() (*SwarmPacket, error) {
	m := new(SwarmPacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *swarmCommunicationClient) ProvisionShortcode(ctx context.Context, in *ShortcodeRequest, opts ...grpc.CallOption) (*ShortcodeResponse, error) {
	out := new(ShortcodeResponse)
	err := c.cc.Invoke(ctx, SwarmCommunication_ProvisionShortcode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmCommunicationClient) GetActiveShortcodes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShortcodeList, error) {
	out := new(ShortcodeList)
	err := c.cc.Invoke(ctx, SwarmCommunication_GetActiveShortcodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmCommunicationClient) ExecuteStrike(ctx context.Context, in *StrikeRequest, opts ...grpc.CallOption) (*StrikeResponse, error) {
	out := new(StrikeResponse)
	err := c.cc.Invoke(ctx, SwarmCommunication_ExecuteStrike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *swarmCommunicationClient) SyncBlackhole(ctx context.Context, opts ...grpc.CallOption) (SwarmCommunication_SyncBlackholeClient, error) {
	stream, err := c.cc.NewStream(ctx, &SwarmCommunication_ServiceDesc.Streams[1], SwarmCommunication_SyncBlackhole_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &swarmCommunicationSyncBlackholeClient{stream}
	return x, nil
}

type SwarmCommunication_SyncBlackholeClient interface {
	Send(*BlackholeUpdate) error
	Recv() (*BlackholeUpdate, error)
	grpc.ClientStream
}

type swarmCommunicationSyncBlackholeClient struct {
	grpc.ClientStream
}

func (x *swarmCommunicationSyncBlackholeClient) Send(m *BlackholeUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *swarmCommunicationSyncBlackholeClient) Recv() (*BlackholeUpdate, error) {
	m := new(BlackholeUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *swarmCommunicationClient) OpenExecutionStream(ctx context.Context, opts ...grpc.CallOption) (SwarmCommunication_OpenExecutionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &SwarmCommunication_ServiceDesc.Streams[2], SwarmCommunication_OpenExecutionStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &swarmCommunicationOpenExecutionStreamClient{stream}
	return x, nil
}

type SwarmCommunication_OpenExecutionStreamClient interface {
	Send(*ExecutionResult) error
	Recv() (*ExecutionRequest, error)
	grpc.ClientStream
}

type swarmCommunicationOpenExecutionStreamClient struct {
	grpc.ClientStream
}

func (x *swarmCommunicationOpenExecutionStreamClient) Send(m *ExecutionResult) error {
	return x.ClientStream.SendMsg(m)
}

func (x *swarmCommunicationOpenExecutionStreamClient) Recv() (*ExecutionRequest, error) {
	m := new(ExecutionRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SwarmCommunicationServer is the server API for SwarmCommunication service.
// All implementations must embed UnimplementedSwarmCommunicationServer
// for forward compatibility
type SwarmCommunicationServer interface {
	// Port 1111: Logged Consensus
	SendPacket(context.Context, *SwarmPacket) (*SwarmPacket, error)
	StreamDeliberation(SwarmCommunication_StreamDeliberationServer) error
	ProvisionShortcode(context.Context, *ShortcodeRequest) (*ShortcodeResponse, error)
	GetActiveShortcodes(context.Context, *Empty) (*ShortcodeList, error)
	// Legacy AELLOK Compatibility
	ExecuteStrike(context.Context, *StrikeRequest) (*StrikeResponse, error)
	SyncBlackhole(SwarmCommunication_SyncBlackholeServer) error
	// SWEN Execution Stream
	OpenExecutionStream(SwarmCommunication_OpenExecutionStreamServer) error
	mustEmbedUnimplementedSwarmCommunicationServer()
}

// UnimplementedSwarmCommunicationServer must be embedded to have forward compatible implementations.
type UnimplementedSwarmCommunicationServer struct {
}

func (UnimplementedSwarmCommunicationServer) SendPacket(context.Context, *SwarmPacket) (*SwarmPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPacket not implemented")
}
func (UnimplementedSwarmCommunicationServer) StreamDeliberation(SwarmCommunication_StreamDeliberationServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamDeliberation not implemented")
}
func (UnimplementedSwarmCommunicationServer) ProvisionShortcode(context.Context, *ShortcodeRequest) (*ShortcodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionShortcode not implemented")
}
func (UnimplementedSwarmCommunicationServer) GetActiveShortcodes(context.Context, *Empty) (*ShortcodeList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveShortcodes not implemented")
}
func (UnimplementedSwarmCommunicationServer) ExecuteStrike(context.Context, *StrikeRequest) (*StrikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteStrike not implemented")
}
func (UnimplementedSwarmCommunicationServer) SyncBlackhole(SwarmCommunication_SyncBlackholeServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncBlackhole not implemented")
}
func (UnimplementedSwarmCommunicationServer) OpenExecutionStream(SwarmCommunication_OpenExecutionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenExecutionStream not implemented")
}
func (UnimplementedSwarmCommunicationServer) mustEmbedUnimplementedSwarmCommunicationServer() {}

// UnsafeSwarmCommunicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwarmCommunicationServer will
// result in compilation errors.
type UnsafeSwarmCommunicationServer interface {
	mustEmbedUnimplementedSwarmCommunicationServer()
}

func RegisterSwarmCommunicationServer(s grpc.ServiceRegistrar, srv SwarmCommunicationServer) {
	s.RegisterService(&SwarmCommunication_ServiceDesc, srv)
}

func _SwarmCommunication_SendPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwarmPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmCommunicationServer).SendPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmCommunication_SendPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmCommunicationServer).SendPacket(ctx, req.(*SwarmPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmCommunication_StreamDeliberation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SwarmCommunicationServer).StreamDeliberation(&swarmCommunicationStreamDeliberationServer{stream})
}

type SwarmCommunication_StreamDeliberationServer interface {
	Send(*SwarmPacket) error
	Recv() (*SwarmPacket, error)
	grpc.ServerStream
}

type swarmCommunicationStreamDeliberationServer struct {
	grpc.ServerStream
}

func (x *swarmCommunicationStreamDeliberationServer) Send(m *SwarmPacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *swarmCommunicationStreamDeliberationServer) Recv() (*SwarmPacket, error) {
	m := new(SwarmPacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SwarmCommunication_ProvisionShortcode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortcodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmCommunicationServer).ProvisionShortcode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmCommunication_ProvisionShortcode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmCommunicationServer).ProvisionShortcode(ctx, req.(*ShortcodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmCommunication_GetActiveShortcodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmCommunicationServer).GetActiveShortcodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmCommunication_GetActiveShortcodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmCommunicationServer).GetActiveShortcodes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmCommunication_ExecuteStrike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwarmCommunicationServer).ExecuteStrike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SwarmCommunication_ExecuteStrike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwarmCommunicationServer).ExecuteStrike(ctx, req.(*StrikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SwarmCommunication_SyncBlackhole_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SwarmCommunicationServer).SyncBlackhole(&swarmCommunicationSyncBlackholeServer{stream})
}

type SwarmCommunication_SyncBlackholeServer interface {
	Send(*BlackholeUpdate) error
	Recv() (*BlackholeUpdate, error)
	grpc.ServerStream
}

type swarmCommunicationSyncBlackholeServer struct {
	grpc.ServerStream
}

func (x *swarmCommunicationSyncBlackholeServer) Send(m *BlackholeUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func (x *swarmCommunicationSyncBlackholeServer) Recv() (*BlackholeUpdate, error) {
	m := new(BlackholeUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SwarmCommunication_OpenExecutionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SwarmCommunicationServer).OpenExecutionStream(&swarmCommunicationOpenExecutionStreamServer{stream})
}

type SwarmCommunication_OpenExecutionStreamServer interface {
	Send(*ExecutionRequest) error
	Recv() (*ExecutionResult, error)
	grpc.ServerStream
}

type swarmCommunicationOpenExecutionStreamServer struct {
	grpc.ServerStream
}

func (x *swarmCommunicationOpenExecutionStreamServer) Send(m *ExecutionRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *swarmCommunicationOpenExecutionStreamServer) Recv() (*ExecutionResult, error) {
	m := new(ExecutionResult)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SwarmCommunication_ServiceDesc is the grpc.ServiceDesc for SwarmCommunication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwarmCommunication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.SwarmCommunication",
	HandlerType: (*SwarmCommunicationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPacket",
			Handler:    _SwarmCommunication_SendPacket_Handler,
		},
		{
			MethodName: "ProvisionShortcode",
			Handler:    _SwarmCommunication_ProvisionShortcode_Handler,
		},
		{
			MethodName: "GetActiveShortcodes",
			Handler:    _SwarmCommunication_GetActiveShortcodes_Handler,
		},
		{
			MethodName: "ExecuteStrike",
			Handler:    _SwarmCommunication_ExecuteStrike_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamDeliberation",
			Handler:       _SwarmCommunication_StreamDeliberation_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncBlackhole",
			Handler:       _SwarmCommunication_SyncBlackhole_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenExecutionStream",
			Handler:       _SwarmCommunication_OpenExecutionStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/swarm.proto",
}

const (
	NeuralGossip_StreamVitality_FullMethodName = "/swarm.NeuralGossip/StreamVitality"
	NeuralGossip_MemoryPageSwap_FullMethodName = "/swarm.NeuralGossip/MemoryPageSwap"
)

// NeuralGossipClient is the client API for NeuralGossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NeuralGossipClient interface {
	StreamVitality(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (NeuralGossip_StreamVitalityClient, error)
	MemoryPageSwap(ctx context.Context, opts ...grpc.CallOption) (NeuralGossip_MemoryPageSwapClient, error)
}

type neuralGossipClient struct {
	cc grpc.ClientConnInterface
}

func NewNeuralGossipClient(cc grpc.ClientConnInterface) NeuralGossipClient {
	return &neuralGossipClient{cc}
}

func (c *neuralGossipClient) StreamVitality(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (NeuralGossip_StreamVitalityClient, error) {
	stream, err := c.cc.NewStream(ctx, &NeuralGossip_ServiceDesc.Streams[0], NeuralGossip_StreamVitality_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &neuralGossipStreamVitalityClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NeuralGossip_StreamVitalityClient interface {
	Recv() (*TelemetryData, error)
	grpc.ClientStream
}

type neuralGossipStreamVitalityClient struct {
	grpc.ClientStream
}

func (x *neuralGossipStreamVitalityClient) Recv() (*TelemetryData, error) {
	m := new(TelemetryData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *neuralGossipClient) MemoryPageSwap(ctx context.Context, opts ...grpc.CallOption) (NeuralGossip_MemoryPageSwapClient, error) {
	stream, err := c.cc.NewStream(ctx, &NeuralGossip_ServiceDesc.Streams[1], NeuralGossip_MemoryPageSwap_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &neuralGossipMemoryPageSwapClient{stream}
	return x, nil
}

type NeuralGossip_MemoryPageSwapClient interface {
	Send(*MemoryPage) error
	Recv() (*MemoryPage, error)
	grpc.ClientStream
}

type neuralGossipMemoryPageSwapClient struct {
	grpc.ClientStream
}

func (x *neuralGossipMemoryPageSwapClient) Send(m *MemoryPage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *neuralGossipMemoryPageSwapClient) Recv() (*MemoryPage, error) {
	m := new(MemoryPage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NeuralGossipServer is the server API for NeuralGossip service.
// All implementations must embed UnimplementedNeuralGossipServer
// for forward compatibility
type NeuralGossipServer interface {
	StreamVitality(*TelemetryRequest, NeuralGossip_StreamVitalityServer) error
	MemoryPageSwap(NeuralGossip_MemoryPageSwapServer) error
	mustEmbedUnimplementedNeuralGossipServer()
}

// UnimplementedNeuralGossipServer must be embedded to have forward compatible implementations.
type UnimplementedNeuralGossipServer struct {
}

func (UnimplementedNeuralGossipServer) StreamVitality(*TelemetryRequest, NeuralGossip_StreamVitalityServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamVitality not implemented")
}
func (UnimplementedNeuralGossipServer) MemoryPageSwap(NeuralGossip_MemoryPageSwapServer) error {
	return status.Errorf(codes.Unimplemented, "method MemoryPageSwap not implemented")
}
func (UnimplementedNeuralGossipServer) mustEmbedUnimplementedNeuralGossipServer() {}

// UnsafeNeuralGossipServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NeuralGossipServer will
// result in compilation errors.
type UnsafeNeuralGossipServer interface {
	mustEmbedUnimplementedNeuralGossipServer()
}

func RegisterNeuralGossipServer(s grpc.ServiceRegistrar, srv NeuralGossipServer) {
	s.RegisterService(&NeuralGossip_ServiceDesc, srv)
}

func _NeuralGossip_StreamVitality_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NeuralGossipServer).StreamVitality(m, &neuralGossipStreamVitalityServer{stream})
}

type NeuralGossip_StreamVitalityServer interface {
	Send(*TelemetryData) error
	grpc.ServerStream
}

type neuralGossipStreamVitalityServer struct {
	grpc.ServerStream
}

func (x *neuralGossipStreamVitalityServer) Send(m *TelemetryData) error {
	return x.ServerStream.SendMsg(m)
}

func _NeuralGossip_MemoryPageSwap_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NeuralGossipServer).MemoryPageSwap(&neuralGossipMemoryPageSwapServer{stream})
}

type NeuralGossip_MemoryPageSwapServer interface {
	Send(*MemoryPage) error
	Recv() (*MemoryPage, error)
	grpc.ServerStream
}

type neuralGossipMemoryPageSwapServer struct {
	grpc.ServerStream
}

func (x *neuralGossipMemoryPageSwapServer) Send(m *MemoryPage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *neuralGossipMemoryPageSwapServer) Recv() (*MemoryPage, error) {
	m := new(MemoryPage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NeuralGossip_ServiceDesc is the grpc.ServiceDesc for NeuralGossip service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NeuralGossip_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.NeuralGossip",
	HandlerType: (*NeuralGossipServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamVitality",
			Handler:       _NeuralGossip_StreamVitality_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MemoryPageSwap",
			Handler:       _NeuralGossip_MemoryPageSwap_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/swarm.proto",
}
