// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/swarm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwarmPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"` // 5alpha# shortcode
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // Target node or 'ALL'
	Intent        string                 `protobuf:"bytes,3,opt,name=intent,proto3" json:"intent,omitempty"`                     // Command/Intent string
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                   // Serialized data
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`              // Unix nanos
	TicketId      string                 `protobuf:"bytes,6,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"` // Associated Fabric Ticket ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwarmPacket) Reset() {
	*x = SwarmPacket{}
	mi := &file_proto_swarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwarmPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwarmPacket) ProtoMessage() {}

func (x *SwarmPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwarmPacket.ProtoReflect.Descriptor instead.
func (*SwarmPacket) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{0}
}

func (x *SwarmPacket) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SwarmPacket) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SwarmPacket) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *SwarmPacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SwarmPacket) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SwarmPacket) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type StrikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	LogicPayload  string                 `protobuf:"bytes,2,opt,name=logic_payload,json=logicPayload,proto3" json:"logic_payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrikeRequest) Reset() {
	*x = StrikeRequest{}
	mi := &file_proto_swarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrikeRequest) ProtoMessage() {}

func (x *StrikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrikeRequest.ProtoReflect.Descriptor instead.
func (*StrikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{1}
}

func (x *StrikeRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *StrikeRequest) GetLogicPayload() string {
	if x != nil {
		return x.LogicPayload
	}
	return ""
}

func (x *StrikeRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type StrikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	LogOutput     string                 `protobuf:"bytes,2,opt,name=log_output,json=logOutput,proto3" json:"log_output,omitempty"`
	ProofHash     string                 `protobuf:"bytes,3,opt,name=proof_hash,json=proofHash,proto3" json:"proof_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrikeResponse) Reset() {
	*x = StrikeResponse{}
	mi := &file_proto_swarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrikeResponse) ProtoMessage() {}

func (x *StrikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrikeResponse.ProtoReflect.Descriptor instead.
func (*StrikeResponse) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{2}
}

func (x *StrikeResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StrikeResponse) GetLogOutput() string {
	if x != nil {
		return x.LogOutput
	}
	return ""
}

func (x *StrikeResponse) GetProofHash() string {
	if x != nil {
		return x.ProofHash
	}
	return ""
}

type BlackholeUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdentifierHash []byte                 `protobuf:"bytes,1,opt,name=identifier_hash,json=identifierHash,proto3" json:"identifier_hash,omitempty"`
	IsRevoked      bool                   `protobuf:"varint,2,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlackholeUpdate) Reset() {
	*x = BlackholeUpdate{}
	mi := &file_proto_swarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackholeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackholeUpdate) ProtoMessage() {}

func (x *BlackholeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackholeUpdate.ProtoReflect.Descriptor instead.
func (*BlackholeUpdate) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{3}
}

func (x *BlackholeUpdate) GetIdentifierHash() []byte {
	if x != nil {
		return x.IdentifierHash
	}
	return nil
}

func (x *BlackholeUpdate) GetIsRevoked() bool {
	if x != nil {
		return x.IsRevoked
	}
	return false
}

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_swarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type TelemetryData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VitalityScore float64                `protobuf:"fixed64,1,opt,name=vitality_score,json=vitalityScore,proto3" json:"vitality_score,omitempty"`
	Slope         float64                `protobuf:"fixed64,2,opt,name=slope,proto3" json:"slope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryData) Reset() {
	*x = TelemetryData{}
	mi := &file_proto_swarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryData) ProtoMessage() {}

func (x *TelemetryData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryData.ProtoReflect.Descriptor instead.
func (*TelemetryData) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{5}
}

func (x *TelemetryData) GetVitalityScore() float64 {
	if x != nil {
		return x.VitalityScore
	}
	return 0
}

func (x *TelemetryData) GetSlope() float64 {
	if x != nil {
		return x.Slope
	}
	return 0
}

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	TargetOs      string                 `protobuf:"bytes,4,opt,name=target_os,json=targetOs,proto3" json:"target_os,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_proto_swarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExecutionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecutionRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecutionRequest) GetTargetOs() string {
	if x != nil {
		return x.TargetOs
	}
	return ""
}

func (x *ExecutionRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ExecutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Logs          []string               `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_proto_swarm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutionResult) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ExecutionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MemoryPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageId        string                 `protobuf:"bytes,1,opt,name=page_id,json=pageId,proto3" json:"page_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryPage) Reset() {
	*x = MemoryPage{}
	mi := &file_proto_swarm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryPage) ProtoMessage() {}

func (x *MemoryPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryPage.ProtoReflect.Descriptor instead.
func (*MemoryPage) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{8}
}

func (x *MemoryPage) GetPageId() string {
	if x != nil {
		return x.PageId
	}
	return ""
}

func (x *MemoryPage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MemoryPage) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ShortcodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortcodeRequest) Reset() {
	*x = ShortcodeRequest{}
	mi := &file_proto_swarm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortcodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortcodeRequest) ProtoMessage() {}

func (x *ShortcodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortcodeRequest.ProtoReflect.Descriptor instead.
func (*ShortcodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{9}
}

func (x *ShortcodeRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ShortcodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shortcode     string                 `protobuf:"bytes,1,opt,name=shortcode,proto3" json:"shortcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortcodeResponse) Reset() {
	*x = ShortcodeResponse{}
	mi := &file_proto_swarm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortcodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortcodeResponse) ProtoMessage() {}

func (x *ShortcodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortcodeResponse.ProtoReflect.Descriptor instead.
func (*ShortcodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{10}
}

func (x *ShortcodeResponse) GetShortcode() string {
	if x != nil {
		return x.Shortcode
	}
	return ""
}

type ShortcodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shortcodes    []string               `protobuf:"bytes,1,rep,name=shortcodes,proto3" json:"shortcodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortcodeList) Reset() {
	*x = ShortcodeList{}
	mi := &file_proto_swarm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortcodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortcodeList) ProtoMessage() {}

func (x *ShortcodeList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortcodeList.ProtoReflect.Descriptor instead.
func (*ShortcodeList) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{11}
}

func (x *ShortcodeList) GetShortcodes() []string {
	if x != nil {
		return x.Shortcodes
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_swarm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_swarm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_swarm_proto_rawDescGZIP(), []int{12}
}

var File_proto_swarm_proto protoreflect.FileDescriptor

const file_proto_swarm_proto_rawDesc = "" +
	"\n" +
	"\x11proto/swarm.proto\x12\x05swarm\"\xb4\x01\n" +
	"\vSwarmPacket\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x16\n" +
	"\x06intent\x18\x03 \x01(\tR\x06intent\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tticket_id\x18\x06 \x01(\tR\bticketId\"o\n" +
	"\rStrikeRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12#\n" +
	"\rlogic_payload\x18\x02 \x01(\tR\flogicPayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"k\n" +
	"\x0eStrikeResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1d\n" +
	"\n" +
	"log_output\x18\x02 \x01(\tR\tlogOutput\x12\x1d\n" +
	"\n" +
	"proof_hash\x18\x03 \x01(\tR\tproofHash\"Y\n" +
	"\x0fBlackholeUpdate\x12'\n" +
	"\x0fidentifier_hash\x18\x01 \x01(\fR\x0eidentifierHash\x12\x1d\n" +
	"\n" +
	"is_revoked\x18\x02 \x01(\bR\tisRevoked\"+\n" +
	"\x10TelemetryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"L\n" +
	"\rTelemetryData\x12%\n" +
	"\x0evitality_score\x18\x01 \x01(\x01R\rvitalityScore\x12\x14\n" +
	"\x05slope\x18\x02 \x01(\x01R\x05slope\"\x96\x01\n" +
	"\x10ExecutionRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x1b\n" +
	"\ttarget_os\x18\x04 \x01(\tR\btargetOs\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\"U\n" +
	"\x0fExecutionResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04logs\x18\x02 \x03(\tR\x04logs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"Q\n" +
	"\n" +
	"MemoryPage\x12\x17\n" +
	"\apage_id\x18\x01 \x01(\tR\x06pageId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"&\n" +
	"\x10ShortcodeRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"1\n" +
	"\x11ShortcodeResponse\x12\x1c\n" +
	"\tshortcode\x18\x01 \x01(\tR\tshortcode\"/\n" +
	"\rShortcodeList\x12\x1e\n" +
	"\n" +
	"shortcodes\x18\x01 \x03(\tR\n" +
	"shortcodes\"\a\n" +
	"\x05Empty2\xdf\x03\n" +
	"\x12SwarmCommunication\x124\n" +
	"\n" +
	"SendPacket\x12\x12.swarm.SwarmPacket\x1a\x12.swarm.SwarmPacket\x12@\n" +
	"\x12StreamDeliberation\x12\x12.swarm.SwarmPacket\x1a\x12.swarm.SwarmPacket(\x010\x01\x12G\n" +
	"\x12ProvisionShortcode\x12\x17.swarm.ShortcodeRequest\x1a\x18.swarm.ShortcodeResponse\x129\n" +
	"\x13GetActiveShortcodes\x12\f.swarm.Empty\x1a\x14.swarm.ShortcodeList\x12<\n" +
	"\rExecuteStrike\x12\x14.swarm.StrikeRequest\x1a\x15.swarm.StrikeResponse\x12C\n" +
	"\rSyncBlackhole\x12\x16.swarm.BlackholeUpdate\x1a\x16.swarm.BlackholeUpdate(\x010\x01\x12J\n" +
	"\x13OpenExecutionStream\x12\x16.swarm.ExecutionResult\x1a\x17.swarm.ExecutionRequest(\x010\x012\x8d\x01\n" +
	"\fNeuralGossip\x12A\n" +
	"\x0eStreamVitality\x12\x17.swarm.TelemetryRequest\x1a\x14.swarm.TelemetryData0\x01\x12:\n" +
	"\x0eMemoryPageSwap\x12\x11.swarm.MemoryPage\x1a\x11.swarm.MemoryPage(\x010\x01B(Z&github.com/thealanphipps-del/pqr/protob\x06proto3"

var (
	file_proto_swarm_proto_rawDescOnce sync.Once
	file_proto_swarm_proto_rawDescData []byte
)

func file_proto_swarm_proto_rawDescGZIP() []byte {
	file_proto_swarm_proto_rawDescOnce.Do(func() {
		file_proto_swarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_swarm_proto_rawDesc), len(file_proto_swarm_proto_rawDesc)))
	})
	return file_proto_swarm_proto_rawDescData
}

var file_proto_swarm_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_swarm_proto_goTypes = []any{
	(*SwarmPacket)(nil),       // 0: swarm.SwarmPacket
	(*StrikeRequest)(nil),     // 1: swarm.StrikeRequest
	(*StrikeResponse)(nil),    // 2: swarm.StrikeResponse
	(*BlackholeUpdate)(nil),   // 3: swarm.BlackholeUpdate
	(*TelemetryRequest)(nil),  // 4: swarm.TelemetryRequest
	(*TelemetryData)(nil),     // 5: swarm.TelemetryData
	(*ExecutionRequest)(nil),  // 6: swarm.ExecutionRequest
	(*ExecutionResult)(nil),   // 7: swarm.ExecutionResult
	(*MemoryPage)(nil),        // 8: swarm.MemoryPage
	(*ShortcodeRequest)(nil),  // 9: swarm.ShortcodeRequest
	(*ShortcodeResponse)(nil), // 10: swarm.ShortcodeResponse
	(*ShortcodeList)(nil),     // 11: swarm.ShortcodeList
	(*Empty)(nil),             // 12: swarm.Empty
}
var file_proto_swarm_proto_depIdxs = []int32{
	0,  // 0: swarm.SwarmCommunication.SendPacket:input_type -> swarm.SwarmPacket
	0,  // 1: swarm.SwarmCommunication.StreamDeliberation:input_type -> swarm.SwarmPacket
	9,  // 2: swarm.SwarmCommunication.ProvisionShortcode:input_type -> swarm.ShortcodeRequest
	12, // 3: swarm.SwarmCommunication.GetActiveShortcodes:input_type -> swarm.Empty
	1,  // 4: swarm.SwarmCommunication.ExecuteStrike:input_type -> swarm.StrikeRequest
	3,  // 5: swarm.SwarmCommunication.SyncBlackhole:input_type -> swarm.BlackholeUpdate
	7,  // 6: swarm.SwarmCommunication.OpenExecutionStream:input_type -> swarm.ExecutionResult
	4,  // 7: swarm.NeuralGossip.StreamVitality:input_type -> swarm.TelemetryRequest
	8,  // 8: swarm.NeuralGossip.MemoryPageSwap:input_type -> swarm.MemoryPage
	0,  // 9: swarm.SwarmCommunication.SendPacket:output_type -> swarm.SwarmPacket
	0,  // 10: swarm.SwarmCommunication.StreamDeliberation:output_type -> swarm.SwarmPacket
	10, // 11: swarm.SwarmCommunication.ProvisionShortcode:output_type -> swarm.ShortcodeResponse
	11, // 12: swarm.SwarmCommunication.GetActiveShortcodes:output_type -> swarm.ShortcodeList
	2,  // 13: swarm.SwarmCommunication.ExecuteStrike:output_type -> swarm.StrikeResponse
	3,  // 14: swarm.SwarmCommunication.SyncBlackhole:output_type -> swarm.BlackholeUpdate
	6,  // 15: swarm.SwarmCommunication.OpenExecutionStream:output_type -> swarm.ExecutionRequest
	5,  // 16: swarm.NeuralGossip.StreamVitality:output_type -> swarm.TelemetryData
	8,  // 17: swarm.NeuralGossip.MemoryPageSwap:output_type -> swarm.MemoryPage
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_swarm_proto_init() }
func file_proto_swarm_proto_init() {
	if File_proto_swarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_swarm_proto_rawDesc), len(file_proto_swarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_swarm_proto_goTypes,
		DependencyIndexes: file_proto_swarm_proto_depIdxs,
		MessageInfos:      file_proto_swarm_proto_msgTypes,
	}.Build()
	File_proto_swarm_proto = out.File
	file_proto_swarm_proto_goTypes = nil
	file_proto_swarm_proto_depIdxs = nil
}
